language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pytest -v

branches:
  only:
  - master
  - "/^f//"
  
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  application: CD_Practice_APP
  deployment_group: ProdEnv
  region: us-east-2
  wait-until-deployed: true
  on:
    branch: master
    condition: NOT test -z "${access_key_id}" AND NOT test -z "${secret_access_key}" 


after_success: 
  - chmod a+x ./travis-automerge-script
  - "BRANCHES_TO_MERGE_REGEX='^f/' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=chiragsoni81245/TestCIPipline ./travis-automerge-script"